# Generated by Django 5.2.7 on 2025-11-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a book entry'), ('can_change_book', 'Can change a book entry'), ('can_delete_book', 'Can delete a book entry')]},
        ),
    ]
